spring.application.name=api-rest

# MongoDB
spring.mongodb.uri=mongodb://admin:admin@localhost:27017/api_rest_spring?authSource=admin&authMechanism=SCRAM-SHA-1

# JWT Configuration
jwt.secret=miClaveSecretaSuperSeguraQueDebeSerMuyLargaParaSeguridad1234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000
